
    - name: update cache
      apt:
        update_cache: yes
      when:
        - ansible_facts['os_family']=="Debian"
        - ansible_facts['distribution_major_version']>= "24"
    - name: install py3 , pip, and virtual vinv
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present
      when:
        - ansible_facts['os_family']=="Debian"
        - ansible_facts['distribution_major_version']>= "24"

    - name: create FastAPI application directory
      file:
        path: /opt/fastapi_app
        state: directory
        mode: '0755'
    - name: copy FastAPI application to destination
      copy:
        src: fastapi_app/
        dest: /opt/fastapi_app
        mode: '0644'

    - name: create virtual env
      command: python3 -m venv /opt/fastapi_app/venv
      args:
        creates: /opt/fastapi_app/venv
    
    - name: install FastAPI and uvicorn in venv
      command: /opt/fastapi_app/venv/bin/pip install fastapi uvicorn
      notify: Print FastAPI installation success

    - name: Run FastAPI application
      shell: |
        nohup /opt/fastapi_app/venv/bin/uvicorn main:app --host 0.0.0.0 --port 8000 &
      args:
        chdir: /opt/fastapi_app